### ISSUE TITLE
Import pad.pad

### ISSUE THREAD

**Issue by peteretep** [pwcazenave/tappy#1]
I'm having trouble using tappy - when I run python tappy.py or import tappy, I get the following error.

```
Traceback (most recent call last):
  File "tappy.py", line 57, in <module>
    import pad.pad as pad
ImportError: No module named pad.pad

```

I can't find the module pad.pad or pad in pip, or anywhere else. Am I missing something obvious?
Thanks.

**Comment by pwcazenave** [comment]
Running tappy.py with python as `python tappy.py` probably won't work with my forked version - you're best off going with the original one from upstream.

How did you install tappy? Did you do a python setup.py?

**Comment by yosoyjay** [comment]
I have the same problem when trying to import using the directions for installation in the README.md file.

I found another repo that does include pad (https://gitlab.ecosystem-modelling.pml.ac.uk/romarine/tappy) and I'm apparently good to go.

**Comment by pwcazenave** [comment]
Thanks - that's a fork of the copy of TAPPY which I have on my work GitLab.

I'm pretty certain that's just a copy of the dev branch, so checking out dev from this repo should get you the same code. I keep meaning to merge into master, but time is never on my side!
